package cn.jc.spider.po;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Jun 03 08:56:09 CST 2012]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ObjectitemPeer
    extends cn.jc.spider.po.BaseObjectitemPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1338684969517L;

}
